# Configuration for .github/workflows/pull_request_label.yml.

'type-infra':
  - changed-files:
      - any-glob-to-any-file: '.github/**'

'package:cronet_http':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/cronet_http/**'

'package:cupertino_http':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/cupertino_http/**'

'package:http':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/http/**'

'package:http_client_conformance_tests':
  - changed-files:
      - any-glob-to-any-file: 'pkgs/http_client_conformance_tests/**'