include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  enable-experiment:
  - non-nullable

linter:
  rules:
  - annotate_overrides
  - avoid_bool_literals_in_conditional_expressions
  - avoid_catching_errors
  - avoid_classes_with_only_static_members
  - avoid_empty_else
  - avoid_function_literals_in_foreach_calls
  - avoid_init_to_null
  - avoid_null_checks_in_equality_operators
  - avoid_private_typedef_functions
  - avoid_redundant_argument_values
  - avoid_relative_lib_imports
  - avoid_renaming_method_parameters
  - avoid_return_types_on_setters
  - avoid_returning_null_for_void
  - avoid_returning_this
  - avoid_shadowing_type_parameters
  - avoid_single_cascade_in_expression_statements
  - avoid_types_as_parameter_names
  - avoid_unused_constructor_parameters
  - await_only_futures
  - camel_case_types
  - cascade_invocations
  # comment_references
  - constant_identifier_names
  - control_flow_in_finally
  - curly_braces_in_flow_control_structures
  - directives_ordering
  - empty_catches
  - empty_constructor_bodies
  - empty_statements
  - file_names
  - hash_and_equals
  - implementation_imports
  - invariant_booleans
  - iterable_contains_unrelated_type
  - join_return_with_assignment
  - library_names
  - library_prefixes
  - lines_longer_than_80_chars
  - list_remove_unrelated_type
  - missing_whitespace_between_adjacent_strings
  - no_adjacent_strings_in_list
  - no_duplicate_case_values
  - no_runtimeType_toString
  - non_constant_identifier_names
  - null_closures
  - omit_local_variable_types
  - only_throw_errors
  - overridden_fields
  - package_names
  - package_prefixed_library_names
  - prefer_adjacent_string_concatenation
  - prefer_asserts_in_initializer_lists
  - prefer_collection_literals
  - prefer_conditional_assignment
  - prefer_const_constructors
  - prefer_const_declarations
  - prefer_contains
  - prefer_equal_for_default_values
  - prefer_expression_function_bodies
  - prefer_final_fields
  #- prefer_final_locals
  - prefer_function_declarations_over_variables
  - prefer_generic_function_type_aliases
  - prefer_initializing_formals
  - prefer_inlined_adds
  - prefer_interpolation_to_compose_strings
  - prefer_is_empty
  - prefer_is_not_empty
  - prefer_is_not_operator
  - prefer_null_aware_operators
  - prefer_relative_imports
  - prefer_single_quotes
  - prefer_typing_uninitialized_variables
  - prefer_void_to_null
  - provide_deprecation_message
  - recursive_getters
  - slash_for_doc_comments
  - sort_pub_dependencies
  - test_types_in_equals
  - throw_in_finally
  - type_annotate_public_apis
  - type_init_formals
  - unawaited_futures
  - unnecessary_brace_in_string_interps
  - unnecessary_const
  - unnecessary_getters_setters
  - unnecessary_lambdas
  - unnecessary_new
  - unnecessary_null_aware_assignments
  - unnecessary_null_in_if_null_operators
  - unnecessary_overrides
  - unnecessary_parenthesis
  - unnecessary_statements
  - unnecessary_string_interpolations
  - unnecessary_this
  - unrelated_type_equality_checks
  - use_is_even_rather_than_modulo
  - use_rethrow_when_possible
  - use_string_buffers
  - valid_regexps
  - void_checks
