include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
  - avoid_bool_literals_in_conditional_expressions
  - avoid_classes_with_only_static_members
  - avoid_private_typedef_functions
  - avoid_returning_this
  - avoid_unused_constructor_parameters
  - cascade_invocations
  - comment_references
  - join_return_with_assignment
  - missing_whitespace_between_adjacent_strings
  - no_adjacent_strings_in_list
  - no_runtimeType_toString
  - prefer_const_constructors
  - prefer_const_declarations
  - prefer_expression_function_bodies
  - prefer_relative_imports
  - test_types_in_equals
  - use_string_buffers
  - use_super_parameters
