// Mocks generated by Mockito 5.4.6 from annotations
// in http2/test/pool_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:http2/src/connection.dart' as _i4;
import 'package:http2/src/settings/settings.dart' as _i2;
import 'package:http2/transport.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeActiveSettings_0 extends _i1.SmartFake
    implements _i2.ActiveSettings {
  _FakeActiveSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientTransportStream_1 extends _i1.SmartFake
    implements _i3.ClientTransportStream {
  _FakeClientTransportStream_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClientConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientConnection extends _i1.Mock implements _i4.ClientConnection {
  MockClientConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOpen =>
      (super.noSuchMethod(Invocation.getter(#isOpen), returnValue: false)
          as bool);

  @override
  _i5.Stream<int> get onPingReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onPingReceived),
            returnValue: _i5.Stream<int>.empty(),
          )
          as _i5.Stream<int>);

  @override
  _i5.Stream<void> get onFrameReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onFrameReceived),
            returnValue: _i5.Stream<void>.empty(),
          )
          as _i5.Stream<void>);

  @override
  _i2.ActiveSettings get acknowledgedSettings =>
      (super.noSuchMethod(
            Invocation.getter(#acknowledgedSettings),
            returnValue: _FakeActiveSettings_0(
              this,
              Invocation.getter(#acknowledgedSettings),
            ),
          )
          as _i2.ActiveSettings);

  @override
  _i2.ActiveSettings get peerSettings =>
      (super.noSuchMethod(
            Invocation.getter(#peerSettings),
            returnValue: _FakeActiveSettings_0(
              this,
              Invocation.getter(#peerSettings),
            ),
          )
          as _i2.ActiveSettings);

  @override
  bool get isClientConnection =>
      (super.noSuchMethod(
            Invocation.getter(#isClientConnection),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> get onInitialPeerSettingsReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onInitialPeerSettingsReceived),
            returnValue: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  set onActiveStateChanged(_i3.ActiveStateHandler? value) => super.noSuchMethod(
    Invocation.setter(#onActiveStateChanged, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.ClientTransportStream makeRequest(
    List<_i3.Header>? headers, {
    bool? endStream = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#makeRequest, [headers], {#endStream: endStream}),
            returnValue: _FakeClientTransportStream_1(
              this,
              Invocation.method(
                #makeRequest,
                [headers],
                {#endStream: endStream},
              ),
            ),
          )
          as _i3.ClientTransportStream);

  @override
  _i5.Future<Object?> ping() =>
      (super.noSuchMethod(
            Invocation.method(#ping, []),
            returnValue: _i5.Future<Object?>.value(),
          )
          as _i5.Future<Object?>);

  @override
  _i5.Future<Object?> finish() =>
      (super.noSuchMethod(
            Invocation.method(#finish, []),
            returnValue: _i5.Future<Object?>.value(),
          )
          as _i5.Future<Object?>);

  @override
  _i5.Future<Object?> terminate([int? errorCode, String? message]) =>
      (super.noSuchMethod(
            Invocation.method(#terminate, [errorCode, message]),
            returnValue: _i5.Future<Object?>.value(),
          )
          as _i5.Future<Object?>);
}
