// Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// This code was generated by the Dart create command with the package template.

import 'dart:io';

import 'package:http/http.dart';
import 'package:java_http/java_http.dart';

void main() async {
  dogFact2();
}

void dogFact() async {
  final client = JavaClient();
  final url = Uri.parse('https://dogapi.dog/api/v2/facts?limit=1');
  final request = Request('GET', url);
  final response = await client.send(request);
  await response.stream.forEach(print);
}

void dogFact2() async {
  final client = JavaClient();
  final url = Uri.parse('https://dogapi.dog/api/v2/facts?limit=1');
  final response = await client.get(url);
  print(response.body);
}

void downloadVideo() async {
  final client = JavaClient();

  final request = Request(
    'GET',
    Uri.parse(
      'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    ),
  );

  final response = await client.send(request);

  var file = File('video.mp4');
  var sink = file.openWrite();
  await sink.addStream(response.stream);
  await sink.close();
}
