name: ios_test
description: Used to execute package:cupertino_http tests on iOS.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # Dependencies required by the the tests in the "test/" directory must be
  # duplicated here.
  convert: ^3.1.1
  crypto: ^3.0.3
  cupertino_http:
    path: ../
  flutter_test:
    sdk: flutter
  http_client_conformance_tests:
    path: ../../http_client_conformance_tests/
  integration_test:
    sdk: flutter
  objective_c: ^9.1.0
  test: ^1.21.1
  web_socket: '^1.0.0'
  web_socket_conformance_tests:
    path: ../../web_socket_conformance_tests/

dependency_overrides:
  http:
    path: ../../http/
