name: Health
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@main
    with:
      sdk: dev
      channel: dev
      flutter_packages: "pkgs/cronet_http,pkgs/cupertino_http,pkgs/ok_http"
    permissions:
      pull-requests: write
