name: Health
permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@ed9c592c1d35106c0a8a52044426515017a60646
    with:
      sdk: dev
      channel: dev
      flutter_packages: "pkgs/cronet_http,pkgs/cupertino_http,pkgs/ok_http"
    permissions:
      pull-requests: write
