name: package:java_http CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/java.yml'
      - 'pkgs/http_client_conformance_tests/**'
      - 'pkgs/java_http/**'
  pull_request:
    paths:
      - '.github/workflows/java.yml'
      - 'pkgs/http_client_conformance_tests/**'
      - 'pkgs/java_http/**'
  schedule:
    # Runs every Sunday at midnight (00:00 UTC).
    - cron: "0 0 * * 0"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  verify:
    name: Format & Analyze & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/java_http
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1
        with:
          channel: 'stable'
      - id: install
        name: Install dependencies
        run: dart pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'
      - name: Analyze code
        run: dart analyze --fatal-infos
        if: always() && steps.install.outcome == 'success'
      - name: Build jni dynamic libraries
        run: dart run jni:setup
      - name: Run tests
        run: dart test
