# A CI configuration to auto-publish pub packages.

name: Publish
permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]
  push:
    tags:
      - '*-v[0-9]+.[0-9]+.[0-9]+'
      - '*-v[0-9]+.[0-9]+.[0-9]+-[A-Za-z0-9]+'

jobs:
  publish:
    if: ${{ github.repository_owner == 'dart-lang' }}
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@cda8bd535dfbcff45010bc3c843d325682f944b2
    with:
      write-comments: false
    permissions:
      id-token: write # Required for authentication using OIDC
      pull-requests: write # Required for writing the pull request note
